### ISSUE TITLE
+auto flag in company init.el

### ISSUE THREAD

**Issue by fauzanrh** [rschmukler/doom.d#1]
I'm curious what is the effect `+auto` flag in your init.el file as i can't find the implementation in the upstream. Thank you

**Comment by rschmukler** [comment]
Hey! Thanks for the interest, hope it's at all-useful.

It looks like a legacy flag that I just never cleaned up. I'll have to remove it some day. It used to enable completion happening as you type - but this has now become the default behavior.

If you're interested in the commit in doom that got rid of it, I traced it down to [04acb8fa](https://github.com/hlissner/doom-emacs/commit/04acb8fa98b822a880b6e218099c8437835b619f#diff-a4d19b4d74e55fcf2626ca737e97c26e)

**Comment by rschmukler** [comment]
I'm going to close this issue to help keep the repo clean! Cheers.
