### ISSUE TITLE
Question on yapfify + emacs doom integration

### ISSUE THREAD

**Issue by c0rv4x** [rschmukler/doom.d#2]
Hey,

I have been trying to install yapf-mode for three days may be and still struggling with it. Your repo is the only place where I found at least some reference on how-to integrate doom and yapf-mode.

So I took this code: https://github.com/rschmukler/doom.d/blob/master/config.el#L252 and installed yapfify.el. I can confirm that `yapfify-buffer` works ok, `yapf-mode` is set to `t`, but the "onsave" formatting is not working. Could you help me here?

I have tried asking in emacs-doom discord, but did not get any response yet. If you feel like not communicating on this, please close/delete the issue, no problem here!

Thanks!

**Comment by c0rv4x** [comment]
Could the problem be that I did not enable `lsp` on python?

**Comment by Camsbury** [comment]
So you can confirm that `yapfify-buffer` is being called on save, but your other formatting isn't working as expected?

**Comment by c0rv4x** [comment]
@Camsbury Sorry for not being precise. I am able to launch `yapfify-buffer` with `M-x`, which formats current buffer. However, formatting does not work on save (I guess, the `yapfify-buffer` command is not being called, otherwise I would have the buffer formatted).

**Comment by rschmukler** [comment]
Hey @c0rvax thanks for checking out the repo.

I presume you added the `before-save` hook to your config as well?

Specifically:

```el
(use-package! yapfify
  :hook
  (python-mode . yapf-mode)
  (before-save . (lambda ()
                   (when (eq major-mode 'python-mode)
                     (yapify-buffer)))))
```

To try troubleshooting further, lets move the code to a proper function, add some printing, and use plain old emacs to configure the hook.

```el
(defun format-python-buffer ()
  (message "Format python buffer called")
  (when (eq major-mode 'python-mode)
    (message "Formatting...")
    (yapify-buffer))

(add-hook 'before-save-hook #'format-python-buffer)
```

After adding the above to the config, try calling `M-x` and invoking `view-echo-area-messages` so we can see whether anything is getting called, etc.

Cheers!

**Comment by c0rv4x** [comment]
Hey @rschmukler

Thanks for such an explicit answer! Wow, that is really helpful!
So, I opened the messages area and I saw that emacs was trying to run `black` which was not installed. Then disabled it with `(setq-hook! 'python-mode-hook +format-with :none)`. 

Now everything works! Thank you so much for your help, much appreciated :heart:
